### ISSUE TITLE
Dimension error while using KT3D.kt3d_asDataFrame3D()

### ISSUE THREAD

**Issue by e-p-metzner** [spatzewind/JKriging#1]
See title and error Log:
```
Number of values must match corresponding dimension length:
    expect 156 but got 128

 com.metzner.enrico.JKriging.helper.DataHelper.printStackTrace(DataHelper.java:700)
 com.metzner.enrico.JKriging.data.DataFrame3D.setDimension(DataFrame3D.java:323)
 com.metzner.enrico.JKriging.kriging.KT3D.kt3d_df(KT3D.java:1408)
 com.metzner.enrico.JKriging.kriging.KT3D.kt3d_asDataFrame3D(KT3D.java:670)
 kriging_itp.work(kriging_itp.java:218)
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 processing.core.PApplet.method(PApplet.java:3860)
 processing.core.PApplet$2.run(PApplet.java:3898)]
java.lang.ArrayIndexOutOfBoundsException: 128
	at com.metzner.enrico.JKriging.data.DataFrame3D.setDimension(DataFrame3D.java:338)
	at com.metzner.enrico.JKriging.kriging.KT3D.kt3d_df(KT3D.java:1408)
	at com.metzner.enrico.JKriging.kriging.KT3D.kt3d_asDataFrame3D(KT3D.java:670)
	at kriging_itp.work(kriging_itp.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.core.PApplet.method(PApplet.java:3860)
	at processing.core.PApplet$2.run(PApplet.java:3898)
```

**Comment by e-p-metzner** [comment]
Solved with commit [227105f509b82fbe4f30eb2b72cfea89fb16a80b](https://github.com/spatzewind/JKriging/commit/227105f509b82fbe4f30eb2b72cfea89fb16a80b).
